# @package __global__
model:
  sequence_length:
    inputs: 512
    targets: 32
  save_checkpoints_steps: 5000
  keep_checkpoint_max: 4

datasets:
  - name: polish_qa
    splits:
      train: ${gs_base_path}/data/polish_qa/dev-0-test-A-input-510.tsv
  - name: trivia_qa_en
    splits:
      train: ${gs_base_path}/data/polish_qa/trivia-qa-train.tsv
  - name: pl_en_qa
    mixture:
      - - polish_qa
        - 0.05
      - trivia_qa_en

train_task: polish_qa
finetune_steps: 20000

predict_files:
  - ${gs_base_path}/data/polish_qa/test-B-questions-510.tsv
